package com.ancs.agpt.system.entity;

import java.io.Serializable;

public class DeptRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_DEPT_ROLE.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_DEPT_ROLE.dept_id
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_DEPT_ROLE.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ANCS_SYSTEM_DEPT_ROLE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_DEPT_ROLE.id
     *
     * @return the value of T_ANCS_SYSTEM_DEPT_ROLE.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_DEPT_ROLE.id
     *
     * @param id the value for T_ANCS_SYSTEM_DEPT_ROLE.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_DEPT_ROLE.dept_id
     *
     * @return the value of T_ANCS_SYSTEM_DEPT_ROLE.dept_id
     *
     * @mbggenerated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_DEPT_ROLE.dept_id
     *
     * @param deptId the value for T_ANCS_SYSTEM_DEPT_ROLE.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_DEPT_ROLE.role_id
     *
     * @return the value of T_ANCS_SYSTEM_DEPT_ROLE.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_DEPT_ROLE.role_id
     *
     * @param roleId the value for T_ANCS_SYSTEM_DEPT_ROLE.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_DEPT_ROLE
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeptRole other = (DeptRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_DEPT_ROLE
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_DEPT_ROLE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deptId=").append(deptId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}