package com.ancs.agpt.system.entity;

import java.io.Serializable;

public class LoginLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_LOGIN_LOG.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_LOGIN_LOG.logname
     *
     * @mbggenerated
     */
    private String logname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_LOGIN_LOG.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_LOGIN_LOG.logintime
     *
     * @mbggenerated
     */
    private String logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_LOGIN_LOG.succeed
     *
     * @mbggenerated
     */
    private Integer succeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_LOGIN_LOG.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ANCS_SYSTEM_LOGIN_LOG
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.ID
     *
     * @return the value of T_ANCS_SYSTEM_LOGIN_LOG.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.ID
     *
     * @param id the value for T_ANCS_SYSTEM_LOGIN_LOG.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.logname
     *
     * @return the value of T_ANCS_SYSTEM_LOGIN_LOG.logname
     *
     * @mbggenerated
     */
    public String getLogname() {
        return logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.logname
     *
     * @param logname the value for T_ANCS_SYSTEM_LOGIN_LOG.logname
     *
     * @mbggenerated
     */
    public void setLogname(String logname) {
        this.logname = logname == null ? null : logname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.userid
     *
     * @return the value of T_ANCS_SYSTEM_LOGIN_LOG.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.userid
     *
     * @param userid the value for T_ANCS_SYSTEM_LOGIN_LOG.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.logintime
     *
     * @return the value of T_ANCS_SYSTEM_LOGIN_LOG.logintime
     *
     * @mbggenerated
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.logintime
     *
     * @param logintime the value for T_ANCS_SYSTEM_LOGIN_LOG.logintime
     *
     * @mbggenerated
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.succeed
     *
     * @return the value of T_ANCS_SYSTEM_LOGIN_LOG.succeed
     *
     * @mbggenerated
     */
    public Integer getSucceed() {
        return succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.succeed
     *
     * @param succeed the value for T_ANCS_SYSTEM_LOGIN_LOG.succeed
     *
     * @mbggenerated
     */
    public void setSucceed(Integer succeed) {
        this.succeed = succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.ip
     *
     * @return the value of T_ANCS_SYSTEM_LOGIN_LOG.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_LOGIN_LOG.ip
     *
     * @param ip the value for T_ANCS_SYSTEM_LOGIN_LOG.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_LOGIN_LOG
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LoginLog other = (LoginLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLogname() == null ? other.getLogname() == null : this.getLogname().equals(other.getLogname()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getLogintime() == null ? other.getLogintime() == null : this.getLogintime().equals(other.getLogintime()))
            && (this.getSucceed() == null ? other.getSucceed() == null : this.getSucceed().equals(other.getSucceed()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_LOGIN_LOG
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLogname() == null) ? 0 : getLogname().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getLogintime() == null) ? 0 : getLogintime().hashCode());
        result = prime * result + ((getSucceed() == null) ? 0 : getSucceed().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_LOGIN_LOG
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", logname=").append(logname);
        sb.append(", userid=").append(userid);
        sb.append(", logintime=").append(logintime);
        sb.append(", succeed=").append(succeed);
        sb.append(", ip=").append(ip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}