package com.ancs.agpt.system.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;

import org.apache.commons.lang.RandomStringUtils;

import com.ancs.agpt.security.sensitive.MaskField;
import com.ancs.agpt.system.entity.enums.Sex;
import com.ancs.agpt.system.entity.enums.Status;
import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.Data;
import lombok.NoArgsConstructor;  
@Data
@NoArgsConstructor
public class User extends SuperEntity{
	
    
	public User(String account, String password, String salt, String name, LocalDate birthday, Sex sex, String email,
			String phone, String telphone, Status status, LocalDateTime lastpswordupdatetime, LocalDateTime createtime, Integer dr, LocalDateTime ts) {
		super();
		this.account = account;
		this.password = password;
		this.salt = salt;
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.telphone = telphone;
		this.status = status;
		this.lastpswordupdatetime = lastpswordupdatetime;
		this.createtime = createtime;
	}


	public User(String account, String password, String name, LocalDate birthday, Sex sex, String email, String phone, String telphone, Status status) {
		// TODO Auto-generated constructor stub
		super();
		this.account = account;
		this.password = password;
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.telphone = telphone;
		this.status = status;
	}
	
	public User(String email, String phone, String telphone,Status status,Date ts) {
		// TODO Auto-generated constructor stub
		super();
		this.email = email;
		this.phone = phone;
		this.telphone = telphone;
		this.status = status;
	}
	
	private Date lastLoginTime;
	
	private String telphone;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.salt
     *
     * @mbggenerated
     */
    private String salt = RandomStringUtils.randomAlphanumeric(20);;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.birthday
     *
     * @mbggenerated
     */
    private LocalDate birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.sex
     *
     * @mbggenerated
     */
    private Sex sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.status
     *
     * @mbggenerated
     */
    private Status status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.lastpswordupdatetime
     *
     * @mbggenerated
     */
    private LocalDateTime lastpswordupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.createtime
     *
     * @mbggenerated
     */
    private LocalDateTime createtime = LocalDateTime.now();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ANCS_SYSTEM_USER
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    
    @MaskField
    public String getPassword() {
    	return this.password;
    }
    
    @MaskField
    public String getSalt() {
    	return this.salt;
    }
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss")
    public LocalDateTime getCreatetime() {
    	return this.createtime;
    }
    
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss")
    public LocalDateTime getLastpswordupdatetime() {
    	return this.lastpswordupdatetime;
    }
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    public LocalDate getBirthday() {
    	return this.birthday;
    }
    
}