package com.ancs.agpt.system.entity;

import java.time.Instant;
import java.util.Date;

import org.apache.commons.lang.RandomStringUtils;

import com.ancs.agpt.system.entity.enums.Sex;
import com.ancs.agpt.system.entity.enums.Status;  

public class User extends SuperEntity{
	
    public User() {
		super();
		// TODO Auto-generated constructor stub
	}
    
	public User(String account, String password, String salt, String name, Date birthday, Sex sex, String email,
			String phone, String telphone, Status status, Date lastpswordupdatetime, Date createtime, Integer dr, Date ts) {
		super();
		this.account = account;
		this.password = password;
		this.salt = salt;
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.telphone = telphone;
		this.status = status;
		this.lastpswordupdatetime = lastpswordupdatetime;
		this.createtime = createtime;
	}


	public User(String account, String password, String name, Date birthday, Sex sex, String email, String phone, String telphone, Status status) {
		// TODO Auto-generated constructor stub
		super();
		this.account = account;
		this.password = password;
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.email = email;
		this.phone = phone;
		this.telphone = telphone;
		this.status = status;
	}
	
	public User(String email, String phone, String telphone,Status status,Date ts) {
		// TODO Auto-generated constructor stub
		super();
		this.email = email;
		this.phone = phone;
		this.telphone = telphone;
		this.status = status;
	}
	
	private Date lastLoginTime;
	
	private String telphone;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.salt
     *
     * @mbggenerated
     */
    private String salt = RandomStringUtils.randomAlphanumeric(20);;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.sex
     *
     * @mbggenerated
     */
    private Sex sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.status
     *
     * @mbggenerated
     */
    private Status status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.lastpswordupdatetime
     *
     * @mbggenerated
     */
    private Date lastpswordupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ANCS_SYSTEM_USER.createtime
     *
     * @mbggenerated
     */
    private Date createtime = Date.from(Instant.now());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ANCS_SYSTEM_USER
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.account
     *
     * @return the value of T_ANCS_SYSTEM_USER.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.account
     *
     * @param account the value for T_ANCS_SYSTEM_USER.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.password
     *
     * @return the value of T_ANCS_SYSTEM_USER.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.password
     *
     * @param password the value for T_ANCS_SYSTEM_USER.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.salt
     *
     * @return the value of T_ANCS_SYSTEM_USER.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.salt
     *
     * @param salt the value for T_ANCS_SYSTEM_USER.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.name
     *
     * @return the value of T_ANCS_SYSTEM_USER.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.name
     *
     * @param name the value for T_ANCS_SYSTEM_USER.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.birthday
     *
     * @return the value of T_ANCS_SYSTEM_USER.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.birthday
     *
     * @param birthday the value for T_ANCS_SYSTEM_USER.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.sex
     *
     * @return the value of T_ANCS_SYSTEM_USER.sex
     *
     * @mbggenerated
     */
    public Sex getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.sex
     *
     * @param sex the value for T_ANCS_SYSTEM_USER.sex
     *
     * @mbggenerated
     */
    public void setSex(Sex sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.email
     *
     * @return the value of T_ANCS_SYSTEM_USER.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.email
     *
     * @param email the value for T_ANCS_SYSTEM_USER.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.phone
     *
     * @return the value of T_ANCS_SYSTEM_USER.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.phone
     *
     * @param phone the value for T_ANCS_SYSTEM_USER.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.status
     *
     * @return the value of T_ANCS_SYSTEM_USER.status
     *
     * @mbggenerated
     */
    public Status getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.status
     *
     * @param status the value for T_ANCS_SYSTEM_USER.status
     *
     * @mbggenerated
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.lastpswordupdatetime
     *
     * @return the value of T_ANCS_SYSTEM_USER.lastpswordupdatetime
     *
     * @mbggenerated
     */
    public Date getLastpswordupdatetime() {
        return lastpswordupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.lastpswordupdatetime
     *
     * @param lastpswordupdatetime the value for T_ANCS_SYSTEM_USER.lastpswordupdatetime
     *
     * @mbggenerated
     */
    public void setLastpswordupdatetime(Date lastpswordupdatetime) {
        this.lastpswordupdatetime = lastpswordupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ANCS_SYSTEM_USER.createtime
     *
     * @return the value of T_ANCS_SYSTEM_USER.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ANCS_SYSTEM_USER.createtime
     *
     * @param createtime the value for T_ANCS_SYSTEM_USER.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

   
    
    public String getTelphone() {
		return telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}
	
	
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_USER
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastpswordupdatetime() == null ? other.getLastpswordupdatetime() == null : this.getLastpswordupdatetime().equals(other.getLastpswordupdatetime()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()))
            && (this.getTelphone() == null ? other.getTelphone() == null : this.getTelphone().equals(other.getTelphone()))
        	&& (this.getLastLoginTime() == null ? other.getLastLoginTime() == null : this.getLastLoginTime().equals(other.getLastLoginTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_USER
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastpswordupdatetime() == null) ? 0 : getLastpswordupdatetime().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        result = prime * result + ((getTelphone() == null) ? 0 : getTelphone().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ANCS_SYSTEM_USER
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(getId());
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", name=").append(name);
        sb.append(", birthday=").append(birthday);
        sb.append(", sex=").append(sex);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", status=").append(status);
        sb.append(", lastpswordupdatetime=").append(lastpswordupdatetime);
        sb.append(", createtime=").append(createtime);
        sb.append(", dr=").append(getDr());
        sb.append(", ts=").append(getTs());
        sb.append(", telphone=").append(telphone);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}